#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : open-isns
Version  : 0.98
Release  : 1
URL      : https://github.com/open-iscsi/open-isns/archive/v0.98.tar.gz
Source0  : https://github.com/open-iscsi/open-isns/archive/v0.98.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: open-isns-bin
Requires: open-isns-config
Requires: open-isns-doc
BuildRequires : openssl-dev

%description
Welcome to Open-iSNS
====================
This is a partial implementation of iSNS, according to RFC4171.
The implementation is still somewhat incomplete, but I'm releasing
it for your reading pleasure.

%package bin
Summary: bin components for the open-isns package.
Group: Binaries
Requires: open-isns-config

%description bin
bin components for the open-isns package.


%package config
Summary: config components for the open-isns package.
Group: Default

%description config
config components for the open-isns package.


%package doc
Summary: doc components for the open-isns package.
Group: Documentation

%description doc
doc components for the open-isns package.


%prep
%setup -q -n open-isns-0.98

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1512431600
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1512431600
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/isnsadm
/usr/bin/isnsd
/usr/bin/isnsdd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/isnsd.service
/usr/lib/systemd/system/isnsd.socket

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*
